import { AdminRole, AdminPermissions } from '../types/admin';

export const ROLE_PERMISSIONS: Record<AdminRole, AdminPermissions> = {
  super: {
    canViewUsers: true,
    canModifyUsers: true,
    canSuspendUsers: true,
    canVerifyUsers: true,
    canViewFinancials: true,
    canModifyPayments: true,
    canHoldPayments: true,
    canReleasePayments: true,
    canViewDisputes: true,
    canResolveDisputes: true,
    canEscalateDisputes: true,
    canViewContracts: true,
    canEnforcePolicy: true,
    canApplyPenalties: true,
    canManageVendors: true,
    canViewVendorData: true,
    canModerateContent: true,
    canRemoveContent: true,
    canViewAnalytics: true,
    canExportData: true,
    canManageAdmins: true,
    canViewAuditLogs: true,
    hasFullOverride: true,
  },
  operations_manager: {
    canViewUsers: true,
    canModifyUsers: true,
    canSuspendUsers: false,
    canVerifyUsers: true,
    canViewFinancials: true,
    canModifyPayments: false,
    canHoldPayments: false,
    canReleasePayments: false,
    canViewDisputes: true,
    canResolveDisputes: false,
    canEscalateDisputes: true,
    canViewContracts: true,
    canEnforcePolicy: false,
    canApplyPenalties: false,
    canManageVendors: true,
    canViewVendorData: true,
    canModerateContent: true,
    canRemoveContent: false,
    canViewAnalytics: true,
    canExportData: true,
    canManageAdmins: false,
    canViewAuditLogs: true,
    hasFullOverride: false,
  },
  compliance_manager: {
    canViewUsers: true,
    canModifyUsers: false,
    canSuspendUsers: true,
    canVerifyUsers: true,
    canViewFinancials: false,
    canModifyPayments: false,
    canHoldPayments: false,
    canReleasePayments: false,
    canViewDisputes: true,
    canResolveDisputes: true,
    canEscalateDisputes: true,
    canViewContracts: true,
    canEnforcePolicy: true,
    canApplyPenalties: true,
    canManageVendors: false,
    canViewVendorData: false,
    canModerateContent: true,
    canRemoveContent: true,
    canViewAnalytics: true,
    canExportData: true,
    canManageAdmins: false,
    canViewAuditLogs: true,
    hasFullOverride: false,
  },
  finance_manager: {
    canViewUsers: true,
    canModifyUsers: false,
    canSuspendUsers: false,
    canVerifyUsers: false,
    canViewFinancials: true,
    canModifyPayments: true,
    canHoldPayments: true,
    canReleasePayments: true,
    canViewDisputes: true,
    canResolveDisputes: true,
    canEscalateDisputes: false,
    canViewContracts: true,
    canEnforcePolicy: false,
    canApplyPenalties: false,
    canManageVendors: false,
    canViewVendorData: false,
    canModerateContent: false,
    canRemoveContent: false,
    canViewAnalytics: true,
    canExportData: true,
    canManageAdmins: false,
    canViewAuditLogs: true,
    hasFullOverride: false,
  },
  support_agent: {
    canViewUsers: true,
    canModifyUsers: false,
    canSuspendUsers: false,
    canVerifyUsers: false,
    canViewFinancials: false,
    canModifyPayments: false,
    canHoldPayments: false,
    canReleasePayments: false,
    canViewDisputes: true,
    canResolveDisputes: false,
    canEscalateDisputes: false,
    canViewContracts: true,
    canEnforcePolicy: false,
    canApplyPenalties: false,
    canManageVendors: false,
    canViewVendorData: false,
    canModerateContent: false,
    canRemoveContent: false,
    canViewAnalytics: false,
    canExportData: false,
    canManageAdmins: false,
    canViewAuditLogs: false,
    hasFullOverride: false,
  },
};

export const getRolePermissions = (role: AdminRole): AdminPermissions => {
  return ROLE_PERMISSIONS[role];
};

export const hasPermission = (
  role: AdminRole,
  permission: keyof AdminPermissions
): boolean => {
  return ROLE_PERMISSIONS[role][permission];
};

export const ROLE_LABELS: Record<AdminRole, string> = {
  super: 'super',
  operations_manager: 'Operations Manager',
  compliance_manager: 'Compliance Manager',
  finance_manager: 'Finance Manager',
  support_agent: 'Support Agent',
};

export const ROLE_DESCRIPTIONS: Record<AdminRole, string> = {
  super: 'Full platform access with override authority (limited to 3 users)',
  operations_manager: 'Workflow monitoring, assignment oversight, vendor operations',
  compliance_manager: 'Credential verification, contract enforcement, policy violations',
  finance_manager: 'Escrow monitoring, payment flows, fee collection',
  support_agent: 'View-only access, ticket responses (limited permissions)',
};
